const express = require('express');
const router = express.Router();
const upload = require('../middleware/uploadMiddleware');

router.post('/', (req, res) => {
    upload.single('image')(req, res, function (err) {
        console.log("UPLOAD ATTEMPTED:", req.file ? req.file.originalname : 'NO FILE SET');
        if (err) {
            console.error('Multer Upload Error:', err);
            return res.status(400).send({ message: err.message || err });
        }
        if (!req.file) {
            console.error('No req.file mapping generated by Multer');
            return res.status(400).send({ message: 'No file received by the server' });
        }
        res.send(`/${req.file.path.replace(/\\/g, '/')}`);
    });
});

module.exports = router;
